### PR TITLE
Wrapper cookbook fixes

### PR DESCRIPTION
**Pull request by lamont**
This solves issue #89 and adds a unit test for same. Essentially I removed any mention of the cookbook source from the custom job resource so that the attribute-set value in the original template definition won't be pointlessly overwritten.

I also applied all the cookstyle recommended fixes.

### CODE REVIEW

**Comment by lamont** [comment]
Travis is failing for reasons I don't understand (kitchen is complaining about a missing cookbook dependency on apt that is clearly there in metadata.rb, plus my local kitchen-vagrant worked). I'm going to keep digging at this, but I'd appreciate a heads up from @elijah or similar saying that I should continue working on getting this PR to pass hound AND travis vs resetting it to just the original unit test and custom resource changes.

**Comment by elijah** [comment]
Do your best, but... i am not sure Travis is particularly reliable of late.

--elijah

**Comment by lamont** [comment]
Boom, travis fixed! I just updated the Gemfile to some latest stuff. I also got a good pointer from Dan Webb on the community chef slack and will open a new PR to use the latest, blessed version of https://github.com/chef-cookbooks/aws/blob/master/.travis.yml which lets us do kitchen via dokken.

Assuming you're happy with this PR (so green!) please merge and version as you see appropriate.

**Comment by lamont** [comment]
Sorry to bother, but I'd like to get a ruling on this PR and merge it if you agree it fixes the issue. It does solve the unit test I added at least, and I got kitchen working again. @elijah are you the party I should ask?

**Comment by elijah** [comment]
Merged. ;-)

**Pull request merged**
